#pvc provisioning
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
  labels:
    app: springboot-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  resources:
    requests:
      storage: 5Gi


